
/**************************************************************
 *	
 *	heal, 8 bit, 11025Hz,
 *	1 channel, 5603 bytes/channel
 *	Total Size: 1 * 5603 + 4 (header) = 5647 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\heal.wav
 *	Time-stamp: Tue Nov 22 11:48:30 2016
 *	
 **************************************************************/

#ifndef __HEALH__
#define __HEALH__

#define HEALFREQ 11025
#define HEALLEN 5603

extern const unsigned char heal[5603];

#endif /* __HEALH__ */
