
/**************************************************************
 *	
 *	healSound, 8 bit, 11025Hz,
 *	2 channel, 5603 bytes/channel
 *	Total Size: 2 * 5603 + 4 (header) = 11250 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\healSound.wav
 *	Time-stamp: Tue Nov 22 09:08:01 2016
 *	
 **************************************************************/

#ifndef __HEALSOUNDH__
#define __HEALSOUNDH__

#define HEALSOUNDFREQ 11025
#define HEALSOUNDLEN 5603

extern const unsigned char healSound_c1[5603];
extern const unsigned char healSound_c2[5603];

#endif /* __HEALSOUNDH__ */
