
/**************************************************************
 *	
 *	swordSound3, 8 bit, 11025Hz,
 *	1 channel, 2068 bytes/channel
 *	Total Size: 1 * 2068 + 4 (header) = 2112 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\swordSound3.wav
 *	Time-stamp: Sat Nov 05 13:04:23 2016
 *	
 **************************************************************/

#ifndef __SWORDSOUND3H__
#define __SWORDSOUND3H__

#define SWORDSOUND3FREQ 11025
#define SWORDSOUND3LEN 2068

extern const unsigned char swordSound3[2068];

#endif /* __SWORDSOUND3H__ */
