
/**************************************************************
 *	
 *	swordSound, 8 bit, 11025Hz,
 *	1 channel, 2618 bytes/channel
 *	Total Size: 1 * 2618 + 4 (header) = 2662 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Music\swordSound.wav
 *	Time-stamp: Mon Oct 31 16:58:15 2016
 *	
 **************************************************************/

#ifndef __SWORDSOUNDH__
#define __SWORDSOUNDH__

#define SWORDSOUNDFREQ 11025
#define SWORDSOUNDLEN 2618

extern const unsigned char swordSound[2618];

#endif /* __SWORDSOUNDH__ */
