
/**************************************************************
 *	
 *	SwordBlock, 8 bit, 11025Hz,
 *	1 channel, 13608 bytes/channel
 *	Total Size: 1 * 13608 + 4 (header) = 13652 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\SwordBlock.wav
 *	Time-stamp: Tue Nov 22 08:47:17 2016
 *	
 **************************************************************/

#ifndef __SWORDBLOCKH__
#define __SWORDBLOCKH__

#define SWORDBLOCKFREQ 11025
#define SWORDBLOCKLEN 13608

extern const unsigned char swordBlock[13608];

#endif /* __SWORDBLOCKH__ */
