
/**************************************************************
 *	
 *	swordSound2, 8 bit, 11025Hz,
 *	1 channel, 2749 bytes/channel
 *	Total Size: 1 * 2749 + 4 (header) = 2793 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\swordSound2.wav
 *	Time-stamp: Sat Nov 05 13:04:19 2016
 *	
 **************************************************************/

#ifndef __SWORDSOUND2H__
#define __SWORDSOUND2H__

#define SWORDSOUND2FREQ 11025
#define SWORDSOUND2LEN 2749

extern const unsigned char swordSound2[2749];

#endif /* __SWORDSOUND2H__ */
