
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 105927 bytes/channel
 *	Total Size: 1 * 105927 + 4 (header) = 105971 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\TitleSong.wav
 *	Time-stamp: Fri Nov 04 16:43:29 2016
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 105927

extern const unsigned char TitleSong[105927];

#endif /* __TITLESONGH__ */
