
/**************************************************************
 *	
 *	Ending, 8 bit, 11025Hz,
 *	1 channel, 423657 bytes/channel
 *	Total Size: 1 * 423657 + 4 (header) = 423701 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\wav2c\Ending.wav
 *	Time-stamp: Mon Dec 12 16:23:44 2016
 *	
 **************************************************************/

#ifndef __ENDINGH__
#define __ENDINGH__

#define ENDINGFREQ 11025
#define ENDINGLEN 423657

extern const unsigned char Ending[423657];

#endif /* __ENDINGH__ */
