
/**************************************************************
 *	
 *	EnemySwordHit, 8 bit, 11025Hz,
 *	1 channel, 8749 bytes/channel
 *	Total Size: 1 * 8749 + 4 (header) = 8793 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\EnemySwordHit.wav
 *	Time-stamp: Tue Nov 22 08:47:05 2016
 *	
 **************************************************************/

#ifndef __ENEMYSWORDHITH__
#define __ENEMYSWORDHITH__

#define ENEMYSWORDHITFREQ 11025
#define ENEMYSWORDHITLEN 8749

extern const unsigned char enemySwordHit[8749];

#endif /* __ENEMYSWORDHITH__ */
