
/**************************************************************
 *	
 *	GameM2, 8 bit, 11025Hz,
 *	1 channel, 423322 bytes/channel
 *	Total Size: 1 * 423322 + 4 (header) = 423366 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\GameM2.wav
 *	Time-stamp: Fri Nov 04 18:11:25 2016
 *	
 **************************************************************/

#ifndef __GAMEM2H__
#define __GAMEM2H__

#define GAMEM2FREQ 11025
#define GAMEM2LEN 423322

extern const unsigned char gameM2[423322];

#endif /* __GAMEM2H__ */
