
/**************************************************************
 *	
 *	gameM1, 8 bit, 11025Hz,
 *	1 channel, 212291 bytes/channel
 *	Total Size: 1 * 212291 + 4 (header) = 212335 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\GameM1.wav
 *	Time-stamp: Fri Nov 04 18:11:17 2016
 *	
 **************************************************************/

#ifndef __GAMEM1H__
#define __GAMEM1H__

#define GAMEM1FREQ 11025
#define GAMEM1LEN 212291

extern const unsigned char gameM1[212291];

#endif /* __GAMEM1H__ */
