
/**************************************************************
 *	
 *	swordSound1, 8 bit, 11025Hz,
 *	1 channel, 2618 bytes/channel
 *	Total Size: 1 * 2618 + 4 (header) = 2662 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\swordSound1.wav
 *	Time-stamp: Sat Nov 05 13:04:14 2016
 *	
 **************************************************************/

#ifndef __SWORDSOUND1H__
#define __SWORDSOUND1H__

#define SWORDSOUND1FREQ 11025
#define SWORDSOUND1LEN 2618

extern const unsigned char swordSound1[2618];

#endif /* __SWORDSOUND1H__ */
