
/**************************************************************
 *	
 *	SwordMiss, 8 bit, 11025Hz,
 *	1 channel, 2809 bytes/channel
 *	Total Size: 1 * 2809 + 4 (header) = 2853 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Michael boal\Dropbox\vba\Ronin3043\Sound\SwordMiss.wav
 *	Time-stamp: Tue Nov 22 08:47:40 2016
 *	
 **************************************************************/

#ifndef __SWORDMISSH__
#define __SWORDMISSH__

#define SWORDMISSFREQ 11025
#define SWORDMISSLEN 2809

extern const unsigned char swordMiss[2809];

#endif /* __SWORDMISSH__ */
